version: "3.1"
services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    ports:
      - "28019:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    restart: always
    secrets:
      - db-password
    links:
      - db
    ports:
      - "5000:5000"
secrets:
  db-password:
    file: db/password.txt